#ifndef JCORD_COLOR_H
#define JCORD_COLOR_H

#include <ncurses.h> //required for color macros

//use default terminal colors for OFF
#define USE_DEFAULT 0

//if no color redefinitions
#define DEFAULT_OFF_BACK COLOR_BLACK
#define DEFAULT_OFF_FRONT COLOR_WHITE
#define DEFAULT_SHROUD_BACK COLOR_BLUE
#define DEFAULT_SHROUD_FRONT COLOR_WHITE
#define DEFAULT_ON_BACK COLOR_BLUE
#define DEFAULT_ON_FRONT COLOR_CYAN

//if color redefinitions
#define USE_CHANGED 1
#define CHANGED_OFF_BACK_INDEX 10
#define CHANGED_OFF_BACK_R 010
#define CHANGED_OFF_BACK_G 010
#define CHANGED_OFF_BACK_B 010
#define CHANGED_OFF_FRONT_INDEX 11
#define CHANGED_OFF_FRONT_R 750
#define CHANGED_OFF_FRONT_G 750
#define CHANGED_OFF_FRONT_B 750
#define CHANGED_SHROUD_BACK_INDEX 12
#define CHANGED_SHROUD_BACK_R 100
#define CHANGED_SHROUD_BACK_G 100
#define CHANGED_SHROUD_BACK_B 250
#define CHANGED_SHROUD_FRONT_INDEX 13
#define CHANGED_SHROUD_FRONT_R 750
#define CHANGED_SHROUD_FRONT_G 750
#define CHANGED_SHROUD_FRONT_B 750
#define CHANGED_ON_BACK_INDEX 14
#define CHANGED_ON_BACK_R 500
#define CHANGED_ON_BACK_G 650
#define CHANGED_ON_BACK_B 800
#define CHANGED_ON_FRONT_INDEX 15
#define CHANGED_ON_FRONT_R 050
#define CHANGED_ON_FRONT_G 150
#define CHANGED_ON_FRONT_B 150

#endif
